### ISSUE TITLE
Building databases takes long, and eats all IO

### ISSUE THREAD

**Issue by o-jasper** [etotheipi/BitcoinArmory#185]
(`ed67a40`, and an earlier version too) Building databases takes long, and eats all IO, even though `bitcoin-qt` already got most of the blockchain. It would be nicer if it didnt take long and didnt use all IO so other applications arent easily bothered.

What is the large amount of data in `~/.armory/databases` for, anyway? Could be decreased? If not all features depend on it, could it be optional?

**Comment by anto** [comment]
I always use Bitcoin-qt so far. I just tried Armory 0.9.23 and I also experience this really annoying issue. 

I am using Bitcoind and Bitcoin-qt v0.11 on Linux x64 with kernel 3.18.18. Python v2.7 and v3.4 are installed. My PC has Intel Core 2 Duo T9400 2.53 GHz, 4 GB RAM and more than 400 GB free space on the hard disk.

It takes just a few minutes for Bitcoin-qt to synchronise with the network. But every time after I close Bitcoin-qt and launch Armory, it is always at the state of "Building Databases" for more than 10 hours even though its database is just a few hours behind the blockchain. My PC is practically unusable when Armory is running as the responses from the keyboard and mouse are very slow. And every time Armory is running, there are always more than 200 TCP connections to 127.0.0.1:8332 in the state of TIME_WAIT.

Is the security features offered by Armory really worth it?

**Comment by droark** [comment]
Armory 0.93.2 (the latest version) uses a totally different DB that should work better. Please try that one.

I'm going to close this one. If people are still having DB issues, I'd like to request that they get in touch with the support channel.
