### ISSUE TITLE
Trezor Support

### ISSUE THREAD

**Issue by PowerPress** [etotheipi/BitcoinArmory#259]
Please add Tezor support to your system. You have a wonderful product and they have a great idea for the hardware wallet. I would love to be able to have armory handle 100% of the software needs for Trezor wallets.

It would make offline storage much cheaper to people that cant afford to purchase a second computer just for bitcoin and greatly enhanced the security.

Thanks

**Comment by pdaian** [comment]
Also worth noting that all wallets that currently support Trezor are either lightweight SPV-only wallets (which leak public keys to all of their selected nodes unless you run and configure your own) or web wallets (which are extremely difficult to use offline or securely).

Armory offering an offline-only graphical solution for Trezor that doesn't leak public keys anywhere would be the next step for security on the Trezor, and could be as secure as command-line tools.  After HD gets added, I'll write a pull request myself if I have to :+1:.

**Comment by droark** [comment]
Thanks for the request. Trezor support is still in the cards. Some other elements, which are almost complete, must be put in place first. We'll revisit once everything is in place.
