### ISSUE TITLE
[0.92.99.1] Armory DB taking forever to rebuild

### ISSUE THREAD

**Issue by zs9099** [etotheipi/BitcoinArmory#260]
![armorydb1](https://cloud.githubusercontent.com/assets/9581489/5695610/55eb8db4-997a-11e4-8569-425a8bef6f16.png)
This was taken on Mac OS X 10.10, I have 16 GB of RAM and roughly 80 MB/s read/write SSHD, yet Armory only uses about 1 MB/s write and about 400 KB/s read.
This is ridiculous. It's 3 days on my windows computer, but it has much better hardware. I pray this is a bug, and it's not going to be like this for long.

**Comment by spaz926** [comment]
Upgrade to 0.93 and see if the problem persists.
I'm on 10.10 an 0.93 works fine.

**Comment by zs9099** [comment]
I am on the 0.93 testing build

**Comment by zs9099** [comment]
0.92.99.3 speeds up DB building
