### ISSUE TITLE
Need to fix clang compile

### ISSUE THREAD

**Issue by yurivict** [etotheipi/BitcoinArmory#277]
Clang breaks on assembly: semicolon isn't a valid statemennt separator, itshould be replaced with "\n\t", see this llvm bug report: https://llvm.org/bugs/show_bug.cgi?id=18916

gcc does understand semicolons as an exception, but they really aren't a valid separator in assembly.

**Comment by yurivict** [comment]
@njaard  Since you are the last who committed into armory, maybe you can fix the clang compile, or you know somebody who cares?

**Comment by njaard** [comment]
Can you provide the error message clang gives you? My version is very old and kind of hopeless.

**Comment by yurivict** [comment]
Yes, see messages.
One problem is that semicolon isn't allowed as statement separator (newline is the separator). But the problem is deeper than that.


clang++ -DNDEBUG -g -O2 -fPIC -DCRYPTOPP_DISABLE_AESNI -pipe -c gzip.cpp
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:20879: note: instantiated into assembly here
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21223: note: instantiated into assembly here
sha.cpp:340:2: error: invalid instruction mnemonic 'prefix'
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21236: note: instantiated into assembly here
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:20879: note: instantiated into assembly here
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21223: note: instantiated into assembly here
sha.cpp:340:2: error: invalid instruction mnemonic 'prefix'
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21236: note: instantiated into assembly here
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:20879: note: instantiated into assembly here
sha.cpp:340:2: error: unknown token in expression
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21223: note: instantiated into assembly here
sha.cpp:340:2: error: invalid instruction mnemonic 'prefix'
        ASL(1)
        ^
./cpu.h:224:17: note: expanded from macro 'ASL'
        #define ASL(x) GNU_ASL(x)
                       ^
./cpu.h:218:26: note: expanded from macro 'GNU_ASL'
        #define GNU_ASL(x) "\n" #x ":"
                                ^
<scratch space>:243:2: note: expanded from here
"1"
 ^
<inline asm>:3:21236: note: instantiated into assembly here
clang++ -DNDEBUG -g -O2 -fPIC -DCRYPTOPP_DISABLE_AESNI -pipe -c dessp.cpp
9 errors generated.

**Comment by njaard** [comment]
Does adding -DCRYPTOPP_DISABLE_ASM to CXXFLAGS in cppForSwig/cryptopp/Makefile 
fix it for you?

**Comment by yurivict** [comment]
Yes, if fixed compile errors. Clang link also failed, I had to add -fPIC to fix it. But after this is builds fine (with some warnings).

**Comment by yurivict** [comment]
Thanks for workaround!

**Comment by droark** [comment]
Hello. Just curious, which OS and version of clang are you using? Everything works fine when compiling on OS X, which uses clang.

**Comment by yurivict** [comment]
FreeBSD 10.1, clang 3.4.1
OSX might be disabling assembly, not sure.
Clang team themselves acknowledged the problem, but they won't fix it for now (see link to llvm bug in my OP). They say projects should fix non-compliant assembly syntax.

**Comment by droark** [comment]
Fixed. See https://github.com/etotheipi/BitcoinArmory/commit/87122c3f15b9c03017094804ddfe3c3dc7571144 for details.
