### ISSUE TITLE
Armoryd Index Error: wallet unusable anymore

### ISSUE THREAD

**Issue by bhugo** [etotheipi/BitcoinArmory#297]
I use armoryd on a regular basis, and today, out of the blue I've got a recurent error on one of my wallets (and only this one).
When I use the RPC command "getledgersimple" python returns an IndexError.

Here is the full traceback:
File "~/BitcoinArmory/armoryengine/Decorators.py", line 79, in inner
rv=func(*args, **kwargs)
File "~/BitcoinArmory/armoryd.py", line 1353, in jsonrpc_getledger
self.serverLBMap.values())
File "~/BitcoinArmory/armoryengine/MultiSigUtils.py", line 125, in scrAddr_to_displayStr
if scrAddr[0] in (SCRADDR_P2PKH_BYTE, SCRADDR_P2SH_BYTE):
IndexError: string out of range

I'm looking into it and I still run my 2 other wallets as usual, I'll update the topic if the situation evolves.

**Comment by AndyOfiesh** [comment]
This is a known issue that will be addressed 0.93.2 which is due out soon.

**Comment by bhugo** [comment]
Thank you for the answer.
