### ISSUE TITLE
Can't load public key for lockbox creation

### ISSUE THREAD

**Issue by R3s1stanc3** [etotheipi/BitcoinArmory#305]
Hi
I wanted to test the Armory Lockbox feature and therefore created 2 wallets.
Both wallets have 2 addresses to recive bitcoins but if I try to create a lockbox and click on the address book icon to load my public key, nothing happenes. I also tried to export the public key manually and then enter it but it didn't work either. I'm using armory 0.93.2 on Arch Linux
Any ideas, how to fix this issue?
greetings

**Comment by droark** [comment]
Hi. Have you filed a support ticket? That would be a better place for this report.

Thanks.
