### ISSUE TITLE
Message Block Verification misbehaves with line carriages

### ISSUE THREAD

**Issue by alexbarcelo** [etotheipi/BitcoinArmory#307]
EDIT: Just realized that I had posted too much personal information. I fear a little bit spammers and automatic crawlers. Tomorrow I'm gonna try to generate a new block verification without any personal info, but maybe someone can replicate the problem.

I was just checking the Signed Message Block in Armory, and stumbled with the following problem. Tried this block:

    -----BEGIN BITCOIN SIGNED MESSAGE-----
    Comment: Signed by Bitcoin Armory v0.93.2

    From: *
    Voat user: *
    -----BEGIN BITCOIN SIGNATURE-----

    HOosm1LrtcLeTCrzbPFsGc97wSsxFRFsk8rtjIsKN2S0w0tJu3cA/LD18U8lDrux
    +jn3cg68R6RsDbKlUI/SXqE=
    =L9oy
    -----END BITCOIN SIGNATURE-----

which works correctly: signed by 1Gq... (which is indeed the signing address).

However, when there are anomalous carriages...

    -----BEGIN BITCOIN SIGNED MESSAGE-----
    Comment: Signed by Bitcoin Armory v0.93.2

    From: *

    Voat user: *
    -----BEGIN BITCOIN SIGNATURE-----

    HOosm1LrtcLeTCrzbPFsGc97wSsxFRFsk8rtjIsKN2S0w0tJu3cA/LD18U8lDrux
    +jn3cg68R6RsDbKlUI/SXqE=
    =L9oy
    -----END BITCOIN SIGNATURE-----

It says that the owner is 1FKwh...
... which is strange. And unexpected.

It is a known issue? Couldn't find it.

**Comment by droark** [comment]
Hello. Just curious, how do the anomalous CRs get there?
