### ISSUE TITLE
Crash if txn amount + fee = more than addresses contain

### ISSUE THREAD

**Issue by gdvine** [etotheipi/BitcoinArmory#347]
OS X v0.95

**Steps to reproduce:**
1. Select "Send"
2. Use Coin Control to select an address
3. Select "MAX" for txn amount
4. Change fee to higher amount
5. Click Continue button

**Expected result:**
Amount automatically reduces to accomodate new fee *OR*
Warning popup informs user the total transaction amount is too high

**Actual result:**
Spinning wheel crash

**Comment by droark** [comment]
[Psst.](https://github.com/etotheipi/BitcoinArmory/issues/341) Please close this out and go to the new repo (and the new [web site](https://btcarmory.com/), and install [0.96.4 RC2](https://github.com/goatpig/BitcoinArmory/releases/)).
