### ISSUE TITLE
Add a disk-persisted cache for blockchain scanning

### ISSUE THREAD

**Issue by strugee** [etotheipi/BitcoinArmory#93]
Every time Armory opens, it rescans the blockchain for transactions, which is annoying as it takes a couple of minutes (at least on my less-than-ideally-powerful ultrabook). Armory should keep a file on disk with data on the portions of the blockchain that it's already processed.

**Comment by strugee** [comment]
@etotheipi I haven't used Armory for a really long time, but this can be closed, right?

**Comment by achow101** [comment]
@strugee Armory development has moved to https://github.com/goatpig/BitcoinArmory. etotheipi is no longer working on Armory and this repo is basically dead (for now).

**Comment by strugee** [comment]
Closing based on the above, thank you.
